CREATE OR REPLACE VIEW RELEASE_VIEW
AS
SELECT DISTINCT RELEASE FROM RELEASE_BRANCH@TLD_REPORTS_DB_LINK 
ORDER BY 1 DESC
/

CREATE OR REPLACE VIEW RUNTYPES_VIEW
AS
SELECT SEQNO, RUN_TYPE, TO_CHAR(RUN_INITIATED_DATE,'DD-MON-YYYY') RUN_INITIATED_DATE, RELEASE
FROM ( SELECT ROWNUM SEQNO, RUN_TYPE, RUN_INITIATED_DATE, RELEASE
        FROM (       
                SELECT DISTINCT MIN(RUN_INITIATED_DATE) RUN_INITIATED_DATE, BUILD_LABEL, RELEASE, RUN_TYPE
                FROM TEST_RUN@TLD_REPORTS_DB_LINK WHERE RUN_INITIATED_DATE IS NOT NULL
                GROUP BY BUILD_LABEL, RELEASE, RUN_TYPE ORDER BY BUILD_LABEL DESC
        ))
ORDER BY SEQNO ASC
/

CREATE OR REPLACE VIEW BUILD_LABEL_VIEW
AS
SELECT DISTINCT BUILD_LABEL, RELEASE 
FROM TEST_RUN@TLD_REPORTS_DB_LINK 
ORDER BY BUILD_LABEL DESC

/

CREATE OR REPLACE VIEW RISK_CATEGORIES_VIEW
AS
SELECT DISTINCT RISK_CATEGORY 
FROM TEST_RUN@TLD_REPORTS_DB_LINK 
ORDER BY 1 ASC

/

CREATE OR REPLACE VIEW CONFIG_TOOL_RELEASE_MAPPINGS_VIEW
AS
SELECT * FROM CONFIG_TOOL_RELEASE_MAPPINGS@TLD_REPORTS_DB_LINK 

/



CREATE OR REPLACE VIEW TEAM_VIEW
AS
SELECT DISTINCT  TEAM
FROM TEST_RUN@TLD_REPORTS_DB_LINK
ORDER BY 1 ASC

/


CREATE OR REPLACE VIEW REGRESSION_REPORT_DATA_VIEW
AS
SELECT * FROM REGRESSION_REPORT_DATA@TLD_REPORTS_DB_LINK
/

CREATE OR REPLACE VIEW BUILD_FAILURE_VIEW
AS
SELECT * FROM BUILD_FAILURE_VIEW@TLD_REPORTS_DB_LINK
/

CREATE OR REPLACE VIEW DUPLICATE_TESTCASE_VIEW
AS
SELECT * FROM DUPLICATE_TESTCASE_VIEW@TLD_REPORTS_DB_LINK 
/


